dist: xenial
addons:
  apt:
    sources:
      - sourceline: 'ppa:snaipewastaken/ppa'
    packages:
      - libyaml-dev
      - protobuf-compiler
      - protobuf-c-compiler
      - criterion-dev
      - criterion

branches:
  only:
  - master

language: c

compiler: gcc

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ctest --extra-verbose
