dist: xenial
addons:
  apt:
    packages:
      - libyaml-dev
      - protobuf-compiler
      - protobuf-c-compiler
      - criterion-dev
      - criterion

branches:
  only:
  - master

language: c

compiler: gcc

script:
  - make
  - cd src/game-state/
  - make tests
  - tests/test-libgamestate
  - cd ../../
