dist: xenial
addons:
  apt:
    sources:
      - sourceline: 'ppa:snaipewastaken/ppa'
    packages:
      - libyaml-dev
      - protobuf-compiler
      - protobuf-c-compiler
      - criterion-dev
      - criterion

branches:
  only:
  - master

language: c

compiler: gcc

before_script:
  - make clean

script:
  - make
  - cd src/game-state/
  - make tests
  - tests/test-libgamestate
  - cd ../../

after_script:
  - make clean
